sonar.projectKey=pinnacle-mailer
sonar.projectName=Pinnacle Mailer
sonar.sourceEncoding=UTF-8
sonar.sources=apps,libs
sonar.tests=apps/backend/src,apps/frontend/src
sonar.exclusions=**/dist/**,**/.next/**,**/storage/**,**/node_modules/**,**/prisma/migrations/**
sonar.coverage.exclusions=**/*.module.ts,**/*.dto.ts,**/*.interface.ts,**/main.ts
sonar.typescript.tsconfigPaths=tsconfig.base.json
